export const SET_STEP = 'SET_STEP'
export const SET_SKILLS = 'SET_SKILLS'
export const SET_BIOGRAPHY = 'SET_BIOGRAPHY'
export const APPROVED = 'APPROVED'
export const LOADING = 'LOADING'
export const SENDED = 'SENDED'
export const ERROR = 'ERROR'
